apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_USERNAME
          value: "root"
        - name: PMA_HOST
          value: "mysql"
        image: phpmyadmin/phpmyadmin:latest
        imagePullPolicy: Always
        name: phpmyadmin
        ports:
        - containerPort: 80
          protocol: TCP
          name: phpmyadmin-port
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30