apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: "8181"
    port: 8181
    targetPort: 80
  selector:
    app: phpmyadmin